@startuml
skinparam sequenceMessageAlign right
"Клиент" -> "Работник склада" : Покупка товара
"Работник склада" -> "Список продукции" : Поиск товара
"Список продукции" -> "Работник склада" : Позиция товара
"Работник склада" -> "Клиент" : Выдача товара


@enduml
