@startuml
left to right direction
actor "Директор" as d
actor "Работник склада" as r
actor "Клиент" as c

legend right
Общая модель деятельности
endlegend

  usecase "Управление остатками " as u1

d -> u1
r --> u1
c --> u1
@enduml
